version: 2.1

jobs:
  deploy:
    docker:
      - image:cimg/node:16.10
    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{checksum "package.json"}}
          - v1-dependencies-

      - run:
          name: Deploy at Netlify
          command: npm run deploy

workflows:
  build_deploy:
    jobs:
      - deploy
